package AppModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 05 14:35:17 IST 2017
// ---------------------------------------------------------------------
public interface contractAM extends ApplicationModule {
    void refreshSearchScreeh();

    void onClickVariation();

    void contractLookup();
}
