package view;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 23 11:45:39 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxscContractLinesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ContLineId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContLineId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContLineId((Number)value);
            }
        },
        ContHeaderId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContHeaderId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContHeaderId((Number)value);
            }
        },
        DataSetId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getDataSetId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setDataSetId((Number)value);
            }
        },
        ProjectId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setProjectId((Number)value);
            }
        },
        ProjectNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getProjectNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setProjectNumber((String)value);
            }
        },
        TaskId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getTaskId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setTaskId((Number)value);
            }
        },
        TaskNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getTaskNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setTaskNumber((String)value);
            }
        },
        PoHeaderId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getPoHeaderId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setPoHeaderId((Number)value);
            }
        },
        PoNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getPoNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setPoNumber((String)value);
            }
        },
        PoLineId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getPoLineId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setPoLineId((Number)value);
            }
        },
        PoLineNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getPoLineNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setPoLineNumber((Number)value);
            }
        },
        ExpenditureTypeId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getExpenditureTypeId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setExpenditureTypeId((Number)value);
            }
        },
        ExpenditureType {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getExpenditureType();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setExpenditureType((String)value);
            }
        },
        ReqHdrId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getReqHdrId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setReqHdrId((Number)value);
            }
        },
        ReqNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getReqNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setReqNumber((String)value);
            }
        },
        ReqLineId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getReqLineId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setReqLineId((Number)value);
            }
        },
        ReqLineNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getReqLineNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setReqLineNumber((Number)value);
            }
        },
        Sno {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getSno();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setSno((Number)value);
            }
        },
        Version {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getVersion();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setVersion((Number)value);
            }
        },
        VersionType {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getVersionType();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setVersionType((String)value);
            }
        },
        LineTypeId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getLineTypeId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setLineTypeId((Number)value);
            }
        },
        ItemNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getItemNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setItemNumber((String)value);
            }
        },
        ItemDescription {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getItemDescription();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        },
        Uom {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getUom();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setUom((String)value);
            }
        },
        OrigQuantity {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getOrigQuantity();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setOrigQuantity((Number)value);
            }
        },
        OrigUnitPrice {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getOrigUnitPrice();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setOrigUnitPrice((Number)value);
            }
        },
        OrigAmount {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getOrigAmount();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setOrigAmount((Number)value);
            }
        },
        VarQuantity {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getVarQuantity();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setVarQuantity((Number)value);
            }
        },
        VarUnitPrice {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getVarUnitPrice();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setVarUnitPrice((Number)value);
            }
        },
        VarAmount {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getVarAmount();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setVarAmount((Number)value);
            }
        },
        RevQuantity {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getRevQuantity();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setRevQuantity((Number)value);
            }
        },
        RevUnitPrice {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getRevUnitPrice();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setRevUnitPrice((Number)value);
            }
        },
        RevAmount {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getRevAmount();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setRevAmount((Number)value);
            }
        },
        AppQuantity {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAppQuantity();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAppQuantity((BigDecimal)value);
            }
        },
        AppUnitPrice {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAppUnitPrice();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAppUnitPrice((BigDecimal)value);
            }
        },
        AppAmount {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAppAmount();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAppAmount((BigDecimal)value);
            }
        },
        CertQuantity {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getCertQuantity();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setCertQuantity((Number)value);
            }
        },
        CertUnitPrice {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getCertUnitPrice();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setCertUnitPrice((Number)value);
            }
        },
        CertAmount {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getCertAmount();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setCertAmount((Number)value);
            }
        },
        CompletionDate {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getCompletionDate();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setCompletionDate((Date)value);
            }
        },
        PercentComplete {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getPercentComplete();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setPercentComplete((Number)value);
            }
        },
        FundedAmount {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getFundedAmount();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setFundedAmount((Number)value);
            }
        },
        InvoicedAmount {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getInvoicedAmount();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setInvoicedAmount((Number)value);
            }
        },
        Comments {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getComments();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setComments((String)value);
            }
        },
        OrgId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        },
        ObjectVersionNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setObjectVersionNumber((Number)value);
            }
        },
        AttributeCategory {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        },
        Attribute1 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        },
        Attribute2 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        },
        Attribute3 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        },
        Attribute4 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        },
        Attribute5 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        },
        Attribute6 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        },
        Attribute7 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        },
        Attribute8 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        },
        Attribute9 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        },
        Attribute10 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        },
        CreatedBy {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        },
        CreationDate {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        },
        LastUpdatedBy {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        },
        LastUpdateDate {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        },
        LastUpdateLogin {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        },
        BoqItemDesc {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getBoqItemDesc();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setBoqItemDesc((String)value);
            }
        },
        CategoryId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getCategoryId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setCategoryId((BigDecimal)value);
            }
        },
        ItemSpec {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getItemSpec();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setItemSpec((String)value);
            }
        },
        CancelReason {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getCancelReason();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setCancelReason((String)value);
            }
        },
        ChangeReason {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getChangeReason();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setChangeReason((String)value);
            }
        },
        NoteToBuyer {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getNoteToBuyer();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setNoteToBuyer((String)value);
            }
        },
        NoteToSupplier {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getNoteToSupplier();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setNoteToSupplier((String)value);
            }
        },
        NeedByDate {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getNeedByDate();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setNeedByDate((Date)value);
            }
        },
        PoStatus {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getPoStatus();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setPoStatus((String)value);
            }
        },
        ContLineNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContLineNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContLineNumber((BigDecimal)value);
            }
        },
        ItemId {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getItemId();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        },
        TaxAmount {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getTaxAmount();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setTaxAmount((Number)value);
            }
        },
        TaxCode {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getTaxCode();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setTaxCode((String)value);
            }
        },
        TaxRate {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getTaxRate();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setTaxRate((Number)value);
            }
        },
        ContractLineNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContractLineNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContractLineNumber((String)value);
            }
        },
        RelLineNumber {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getRelLineNumber();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setRelLineNumber((String)value);
            }
        },
        Variation {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getVariation();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setVariation((String)value);
            }
        },
        EcpPercentage {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getEcpPercentage();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setEcpPercentage((Number)value);
            }
        },
        EcpTotalAmount {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getEcpTotalAmount();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setEcpTotalAmount((Number)value);
            }
        },
        ContLinePageNo {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContLinePageNo();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContLinePageNo((String)value);
            }
        },
        ContLineItemNo {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContLineItemNo();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContLineItemNo((String)value);
            }
        },
        ContLineBillDtls {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContLineBillDtls();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContLineBillDtls((String)value);
            }
        },
        LineAmtRemark {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getLineAmtRemark();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setLineAmtRemark((String)value);
            }
        },
        CategoryName_Tarns {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getCategoryName_Tarns();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setCategoryName_Tarns((String)value);
            }
        },
        ContAdv {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContAdv();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContAdv((Number)value);
            }
        },
        ContAdvAmt {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContAdvAmt();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContAdvAmt((Number)value);
            }
        },
        ContAdvRec {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContAdvRec();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContAdvRec((Number)value);
            }
        },
        ContAdvRecAmt {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContAdvRecAmt();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContAdvRecAmt((Number)value);
            }
        },
        ContRet {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContRet();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContRet((Number)value);
            }
        },
        ContRetAmt {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContRetAmt();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContRetAmt((Number)value);
            }
        },
        ContRetRec {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContRetRec();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContRetRec((Number)value);
            }
        },
        ContRetRecAmt {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getContRetRecAmt();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setContRetRecAmt((Number)value);
            }
        },
        XxscContractHeadersVO {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getXxscContractHeadersVO();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        XxscContractDelPlanVO {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getXxscContractDelPlanVO();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        XxscAttachmentVO {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getXxscAttachmentVO();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        prROVA {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getprROVA();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        poROVA {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getpoROVA();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        projectTask_ROVA {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getprojectTask_ROVA();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        UOM_ROVA {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getUOM_ROVA();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        prLine_ROVA {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getprLine_ROVA();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        poLineROVA {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getpoLineROVA();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        UOM_ROVA_E {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getUOM_ROVA_E();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        categoryROVA {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getcategoryROVA();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        categoryROVA_E {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getcategoryROVA_E();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        Variation_ROVO1 {
            public Object get(XxscContractLinesVORowImpl obj) {
                return obj.getVariation_ROVO1();
            }

            public void put(XxscContractLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxscContractLinesVORowImpl object);

        public abstract void put(XxscContractLinesVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CONTLINEID = AttributesEnum.ContLineId.index();
    public static final int CONTHEADERID = AttributesEnum.ContHeaderId.index();
    public static final int DATASETID = AttributesEnum.DataSetId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int PROJECTNUMBER =
        AttributesEnum.ProjectNumber.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int TASKNUMBER = AttributesEnum.TaskNumber.index();
    public static final int POHEADERID = AttributesEnum.PoHeaderId.index();
    public static final int PONUMBER = AttributesEnum.PoNumber.index();
    public static final int POLINEID = AttributesEnum.PoLineId.index();
    public static final int POLINENUMBER = AttributesEnum.PoLineNumber.index();
    public static final int EXPENDITURETYPEID =
        AttributesEnum.ExpenditureTypeId.index();
    public static final int EXPENDITURETYPE =
        AttributesEnum.ExpenditureType.index();
    public static final int REQHDRID = AttributesEnum.ReqHdrId.index();
    public static final int REQNUMBER = AttributesEnum.ReqNumber.index();
    public static final int REQLINEID = AttributesEnum.ReqLineId.index();
    public static final int REQLINENUMBER =
        AttributesEnum.ReqLineNumber.index();
    public static final int SNO = AttributesEnum.Sno.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int VERSIONTYPE = AttributesEnum.VersionType.index();
    public static final int LINETYPEID = AttributesEnum.LineTypeId.index();
    public static final int ITEMNUMBER = AttributesEnum.ItemNumber.index();
    public static final int ITEMDESCRIPTION =
        AttributesEnum.ItemDescription.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int ORIGQUANTITY = AttributesEnum.OrigQuantity.index();
    public static final int ORIGUNITPRICE =
        AttributesEnum.OrigUnitPrice.index();
    public static final int ORIGAMOUNT = AttributesEnum.OrigAmount.index();
    public static final int VARQUANTITY = AttributesEnum.VarQuantity.index();
    public static final int VARUNITPRICE = AttributesEnum.VarUnitPrice.index();
    public static final int VARAMOUNT = AttributesEnum.VarAmount.index();
    public static final int REVQUANTITY = AttributesEnum.RevQuantity.index();
    public static final int REVUNITPRICE = AttributesEnum.RevUnitPrice.index();
    public static final int REVAMOUNT = AttributesEnum.RevAmount.index();
    public static final int APPQUANTITY = AttributesEnum.AppQuantity.index();
    public static final int APPUNITPRICE = AttributesEnum.AppUnitPrice.index();
    public static final int APPAMOUNT = AttributesEnum.AppAmount.index();
    public static final int CERTQUANTITY = AttributesEnum.CertQuantity.index();
    public static final int CERTUNITPRICE =
        AttributesEnum.CertUnitPrice.index();
    public static final int CERTAMOUNT = AttributesEnum.CertAmount.index();
    public static final int COMPLETIONDATE =
        AttributesEnum.CompletionDate.index();
    public static final int PERCENTCOMPLETE =
        AttributesEnum.PercentComplete.index();
    public static final int FUNDEDAMOUNT = AttributesEnum.FundedAmount.index();
    public static final int INVOICEDAMOUNT =
        AttributesEnum.InvoicedAmount.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int OBJECTVERSIONNUMBER =
        AttributesEnum.ObjectVersionNumber.index();
    public static final int ATTRIBUTECATEGORY =
        AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE =
        AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN =
        AttributesEnum.LastUpdateLogin.index();
    public static final int BOQITEMDESC = AttributesEnum.BoqItemDesc.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int ITEMSPEC = AttributesEnum.ItemSpec.index();
    public static final int CANCELREASON = AttributesEnum.CancelReason.index();
    public static final int CHANGEREASON = AttributesEnum.ChangeReason.index();
    public static final int NOTETOBUYER = AttributesEnum.NoteToBuyer.index();
    public static final int NOTETOSUPPLIER =
        AttributesEnum.NoteToSupplier.index();
    public static final int NEEDBYDATE = AttributesEnum.NeedByDate.index();
    public static final int POSTATUS = AttributesEnum.PoStatus.index();
    public static final int CONTLINENUMBER =
        AttributesEnum.ContLineNumber.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int TAXAMOUNT = AttributesEnum.TaxAmount.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int TAXRATE = AttributesEnum.TaxRate.index();
    public static final int CONTRACTLINENUMBER =
        AttributesEnum.ContractLineNumber.index();
    public static final int RELLINENUMBER =
        AttributesEnum.RelLineNumber.index();
    public static final int VARIATION = AttributesEnum.Variation.index();
    public static final int ECPPERCENTAGE =
        AttributesEnum.EcpPercentage.index();
    public static final int ECPTOTALAMOUNT =
        AttributesEnum.EcpTotalAmount.index();
    public static final int CONTLINEPAGENO =
        AttributesEnum.ContLinePageNo.index();
    public static final int CONTLINEITEMNO =
        AttributesEnum.ContLineItemNo.index();
    public static final int CONTLINEBILLDTLS =
        AttributesEnum.ContLineBillDtls.index();
    public static final int LINEAMTREMARK =
        AttributesEnum.LineAmtRemark.index();
    public static final int CATEGORYNAME_TARNS =
        AttributesEnum.CategoryName_Tarns.index();
    public static final int CONTADV = AttributesEnum.ContAdv.index();
    public static final int CONTADVAMT = AttributesEnum.ContAdvAmt.index();
    public static final int CONTADVREC = AttributesEnum.ContAdvRec.index();
    public static final int CONTADVRECAMT =
        AttributesEnum.ContAdvRecAmt.index();
    public static final int CONTRET = AttributesEnum.ContRet.index();
    public static final int CONTRETAMT = AttributesEnum.ContRetAmt.index();
    public static final int CONTRETREC = AttributesEnum.ContRetRec.index();
    public static final int CONTRETRECAMT =
        AttributesEnum.ContRetRecAmt.index();
    public static final int XXSCCONTRACTHEADERSVO =
        AttributesEnum.XxscContractHeadersVO.index();
    public static final int XXSCCONTRACTDELPLANVO =
        AttributesEnum.XxscContractDelPlanVO.index();
    public static final int XXSCATTACHMENTVO =
        AttributesEnum.XxscAttachmentVO.index();
    public static final int PRROVA = AttributesEnum.prROVA.index();
    public static final int POROVA = AttributesEnum.poROVA.index();
    public static final int PROJECTTASK_ROVA =
        AttributesEnum.projectTask_ROVA.index();
    public static final int UOM_ROVA = AttributesEnum.UOM_ROVA.index();
    public static final int PRLINE_ROVA = AttributesEnum.prLine_ROVA.index();
    public static final int POLINEROVA = AttributesEnum.poLineROVA.index();
    public static final int UOM_ROVA_E = AttributesEnum.UOM_ROVA_E.index();
    public static final int CATEGORYROVA = AttributesEnum.categoryROVA.index();
    public static final int CATEGORYROVA_E =
        AttributesEnum.categoryROVA_E.index();
    public static final int VARIATION_ROVO1 =
        AttributesEnum.Variation_ROVO1.index();


    /**
     * This is the default constructor (do not remove).
     */
    public XxscContractLinesVORowImpl() {
    }

    /**
     * Gets XxscContractLinesEO entity object.
     * @return the XxscContractLinesEO
     */
    public EntityImpl getXxscContractLinesEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CONT_LINE_ID using the alias name ContLineId.
     * @return the CONT_LINE_ID
     */
    public Number getContLineId() {
        return (Number)getAttributeInternal(CONTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_LINE_ID using the alias name ContLineId.
     * @param value value to set the CONT_LINE_ID
     */
    public void setContLineId(Number value) {
        setAttributeInternal(CONTLINEID, value);
    }

    /**
     * Gets the attribute value for CONT_HEADER_ID using the alias name ContHeaderId.
     * @return the CONT_HEADER_ID
     */
    public Number getContHeaderId() {
        return (Number)getAttributeInternal(CONTHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_HEADER_ID using the alias name ContHeaderId.
     * @param value value to set the CONT_HEADER_ID
     */
    public void setContHeaderId(Number value) {
        setAttributeInternal(CONTHEADERID, value);
    }

    /**
     * Gets the attribute value for DATA_SET_ID using the alias name DataSetId.
     * @return the DATA_SET_ID
     */
    public Number getDataSetId() {
        return (Number)getAttributeInternal(DATASETID);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_SET_ID using the alias name DataSetId.
     * @param value value to set the DATA_SET_ID
     */
    public void setDataSetId(Number value) {
        setAttributeInternal(DATASETID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public Number getProjectId() {
        return (Number)getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for PROJECT_NUMBER using the alias name ProjectNumber.
     * @return the PROJECT_NUMBER
     */
    public String getProjectNumber() {
        return (String)getAttributeInternal(PROJECTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_NUMBER using the alias name ProjectNumber.
     * @param value value to set the PROJECT_NUMBER
     */
    public void setProjectNumber(String value) {
        setAttributeInternal(PROJECTNUMBER, value);
    }

    /**
     * Gets the attribute value for TASK_ID using the alias name TaskId.
     * @return the TASK_ID
     */
    public Number getTaskId() {
        return (Number)getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_ID using the alias name TaskId.
     * @param value value to set the TASK_ID
     */
    public void setTaskId(Number value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for TASK_NUMBER using the alias name TaskNumber.
     * @return the TASK_NUMBER
     */
    public String getTaskNumber() {
        return (String)getAttributeInternal(TASKNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_NUMBER using the alias name TaskNumber.
     * @param value value to set the TASK_NUMBER
     */
    public void setTaskNumber(String value) {
        setAttributeInternal(TASKNUMBER, value);
    }

    /**
     * Gets the attribute value for PO_HEADER_ID using the alias name PoHeaderId.
     * @return the PO_HEADER_ID
     */
    public Number getPoHeaderId() {
        return (Number)getAttributeInternal(POHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_HEADER_ID using the alias name PoHeaderId.
     * @param value value to set the PO_HEADER_ID
     */
    public void setPoHeaderId(Number value) {
        setAttributeInternal(POHEADERID, value);
    }

    /**
     * Gets the attribute value for PO_NUMBER using the alias name PoNumber.
     * @return the PO_NUMBER
     */
    public String getPoNumber() {
        return (String)getAttributeInternal(PONUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_NUMBER using the alias name PoNumber.
     * @param value value to set the PO_NUMBER
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }

    /**
     * Gets the attribute value for PO_LINE_ID using the alias name PoLineId.
     * @return the PO_LINE_ID
     */
    public Number getPoLineId() {
        return (Number)getAttributeInternal(POLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_LINE_ID using the alias name PoLineId.
     * @param value value to set the PO_LINE_ID
     */
    public void setPoLineId(Number value) {
        setAttributeInternal(POLINEID, value);
    }

    /**
     * Gets the attribute value for PO_LINE_NUMBER using the alias name PoLineNumber.
     * @return the PO_LINE_NUMBER
     */
    public Number getPoLineNumber() {
        return (Number)getAttributeInternal(POLINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_LINE_NUMBER using the alias name PoLineNumber.
     * @param value value to set the PO_LINE_NUMBER
     */
    public void setPoLineNumber(Number value) {
        setAttributeInternal(POLINENUMBER, value);
    }

    /**
     * Gets the attribute value for EXPENDITURE_TYPE_ID using the alias name ExpenditureTypeId.
     * @return the EXPENDITURE_TYPE_ID
     */
    public Number getExpenditureTypeId() {
        return (Number)getAttributeInternal(EXPENDITURETYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPENDITURE_TYPE_ID using the alias name ExpenditureTypeId.
     * @param value value to set the EXPENDITURE_TYPE_ID
     */
    public void setExpenditureTypeId(Number value) {
        setAttributeInternal(EXPENDITURETYPEID, value);
    }

    /**
     * Gets the attribute value for EXPENDITURE_TYPE using the alias name ExpenditureType.
     * @return the EXPENDITURE_TYPE
     */
    public String getExpenditureType() {
        return (String)getAttributeInternal(EXPENDITURETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPENDITURE_TYPE using the alias name ExpenditureType.
     * @param value value to set the EXPENDITURE_TYPE
     */
    public void setExpenditureType(String value) {
        setAttributeInternal(EXPENDITURETYPE, value);
    }

    /**
     * Gets the attribute value for REQ_HDR_ID using the alias name ReqHdrId.
     * @return the REQ_HDR_ID
     */
    public Number getReqHdrId() {
        return (Number)getAttributeInternal(REQHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_HDR_ID using the alias name ReqHdrId.
     * @param value value to set the REQ_HDR_ID
     */
    public void setReqHdrId(Number value) {
        setAttributeInternal(REQHDRID, value);
    }

    /**
     * Gets the attribute value for REQ_NUMBER using the alias name ReqNumber.
     * @return the REQ_NUMBER
     */
    public String getReqNumber() {
        return (String)getAttributeInternal(REQNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_NUMBER using the alias name ReqNumber.
     * @param value value to set the REQ_NUMBER
     */
    public void setReqNumber(String value) {
        setAttributeInternal(REQNUMBER, value);
    }

    /**
     * Gets the attribute value for REQ_LINE_ID using the alias name ReqLineId.
     * @return the REQ_LINE_ID
     */
    public Number getReqLineId() {
        return (Number)getAttributeInternal(REQLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_LINE_ID using the alias name ReqLineId.
     * @param value value to set the REQ_LINE_ID
     */
    public void setReqLineId(Number value) {
        setAttributeInternal(REQLINEID, value);
    }

    /**
     * Gets the attribute value for REQ_LINE_NUMBER using the alias name ReqLineNumber.
     * @return the REQ_LINE_NUMBER
     */
    public Number getReqLineNumber() {
        return (Number)getAttributeInternal(REQLINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_LINE_NUMBER using the alias name ReqLineNumber.
     * @param value value to set the REQ_LINE_NUMBER
     */
    public void setReqLineNumber(Number value) {
        setAttributeInternal(REQLINENUMBER, value);
    }

    /**
     * Gets the attribute value for SNO using the alias name Sno.
     * @return the SNO
     */
    public Number getSno() {
        return (Number)getAttributeInternal(SNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SNO using the alias name Sno.
     * @param value value to set the SNO
     */
    public void setSno(Number value) {
        setAttributeInternal(SNO, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public Number getVersion() {
        return (Number)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(Number value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for VERSION_TYPE using the alias name VersionType.
     * @return the VERSION_TYPE
     */
    public String getVersionType() {
        return (String)getAttributeInternal(VERSIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_TYPE using the alias name VersionType.
     * @param value value to set the VERSION_TYPE
     */
    public void setVersionType(String value) {
        setAttributeInternal(VERSIONTYPE, value);
    }

    /**
     * Gets the attribute value for LINE_TYPE_ID using the alias name LineTypeId.
     * @return the LINE_TYPE_ID
     */
    public Number getLineTypeId() {
        return (Number)getAttributeInternal(LINETYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_TYPE_ID using the alias name LineTypeId.
     * @param value value to set the LINE_TYPE_ID
     */
    public void setLineTypeId(Number value) {
        setAttributeInternal(LINETYPEID, value);
    }

    /**
     * Gets the attribute value for ITEM_NUMBER using the alias name ItemNumber.
     * @return the ITEM_NUMBER
     */
    public String getItemNumber() {
        return (String)getAttributeInternal(ITEMNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_NUMBER using the alias name ItemNumber.
     * @param value value to set the ITEM_NUMBER
     */
    public void setItemNumber(String value) {
        setAttributeInternal(ITEMNUMBER, value);
    }

    /**
     * Gets the attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @return the ITEM_DESCRIPTION
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @param value value to set the ITEM_DESCRIPTION
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for ORIG_QUANTITY using the alias name OrigQuantity.
     * @return the ORIG_QUANTITY
     */
    public Number getOrigQuantity() {
        return (Number)getAttributeInternal(ORIGQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORIG_QUANTITY using the alias name OrigQuantity.
     * @param value value to set the ORIG_QUANTITY
     */
    public void setOrigQuantity(Number value) {
        setAttributeInternal(ORIGQUANTITY, value);
    }

    /**
     * Gets the attribute value for ORIG_UNIT_PRICE using the alias name OrigUnitPrice.
     * @return the ORIG_UNIT_PRICE
     */
    public Number getOrigUnitPrice() {
        return (Number)getAttributeInternal(ORIGUNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORIG_UNIT_PRICE using the alias name OrigUnitPrice.
     * @param value value to set the ORIG_UNIT_PRICE
     */
    public void setOrigUnitPrice(Number value) {
        setAttributeInternal(ORIGUNITPRICE, value);
    }

    /**
     * Gets the attribute value for ORIG_AMOUNT using the alias name OrigAmount.
     * @return the ORIG_AMOUNT
     */
    public Number getOrigAmount() {
        return (Number)getAttributeInternal(ORIGAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for ORIG_AMOUNT using the alias name OrigAmount.
     * @param value value to set the ORIG_AMOUNT
     */
    public void setOrigAmount(Number value) {
        setAttributeInternal(ORIGAMOUNT, value);
    }

    /**
     * Gets the attribute value for VAR_QUANTITY using the alias name VarQuantity.
     * @return the VAR_QUANTITY
     */
    public Number getVarQuantity() {
        return (Number)getAttributeInternal(VARQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for VAR_QUANTITY using the alias name VarQuantity.
     * @param value value to set the VAR_QUANTITY
     */
    public void setVarQuantity(Number value) {
        setAttributeInternal(VARQUANTITY, value);
    }

    /**
     * Gets the attribute value for VAR_UNIT_PRICE using the alias name VarUnitPrice.
     * @return the VAR_UNIT_PRICE
     */
    public Number getVarUnitPrice() {
        return (Number)getAttributeInternal(VARUNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for VAR_UNIT_PRICE using the alias name VarUnitPrice.
     * @param value value to set the VAR_UNIT_PRICE
     */
    public void setVarUnitPrice(Number value) {
        setAttributeInternal(VARUNITPRICE, value);
    }

    /**
     * Gets the attribute value for VAR_AMOUNT using the alias name VarAmount.
     * @return the VAR_AMOUNT
     */
    public Number getVarAmount() {
        return (Number)getAttributeInternal(VARAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for VAR_AMOUNT using the alias name VarAmount.
     * @param value value to set the VAR_AMOUNT
     */
    public void setVarAmount(Number value) {
        setAttributeInternal(VARAMOUNT, value);
    }

    /**
     * Gets the attribute value for REV_QUANTITY using the alias name RevQuantity.
     * @return the REV_QUANTITY
     */
    public Number getRevQuantity() {
        return (Number)getAttributeInternal(REVQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for REV_QUANTITY using the alias name RevQuantity.
     * @param value value to set the REV_QUANTITY
     */
    public void setRevQuantity(Number value) {
        setAttributeInternal(REVQUANTITY, value);
    }

    /**
     * Gets the attribute value for REV_UNIT_PRICE using the alias name RevUnitPrice.
     * @return the REV_UNIT_PRICE
     */
    public Number getRevUnitPrice() {
        return (Number)getAttributeInternal(REVUNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for REV_UNIT_PRICE using the alias name RevUnitPrice.
     * @param value value to set the REV_UNIT_PRICE
     */
    public void setRevUnitPrice(Number value) {
        setAttributeInternal(REVUNITPRICE, value);
    }

    /**
     * Gets the attribute value for REV_AMOUNT using the alias name RevAmount.
     * @return the REV_AMOUNT
     */
    public Number getRevAmount() {
        return (Number)getAttributeInternal(REVAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for REV_AMOUNT using the alias name RevAmount.
     * @param value value to set the REV_AMOUNT
     */
    public void setRevAmount(Number value) {
        setAttributeInternal(REVAMOUNT, value);
    }

    /**
     * Gets the attribute value for APP_QUANTITY using the alias name AppQuantity.
     * @return the APP_QUANTITY
     */
    public BigDecimal getAppQuantity() {
        return (BigDecimal)getAttributeInternal(APPQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_QUANTITY using the alias name AppQuantity.
     * @param value value to set the APP_QUANTITY
     */
    public void setAppQuantity(BigDecimal value) {
        setAttributeInternal(APPQUANTITY, value);
    }

    /**
     * Gets the attribute value for APP_UNIT_PRICE using the alias name AppUnitPrice.
     * @return the APP_UNIT_PRICE
     */
    public BigDecimal getAppUnitPrice() {
        return (BigDecimal)getAttributeInternal(APPUNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_UNIT_PRICE using the alias name AppUnitPrice.
     * @param value value to set the APP_UNIT_PRICE
     */
    public void setAppUnitPrice(BigDecimal value) {
        setAttributeInternal(APPUNITPRICE, value);
    }

    /**
     * Gets the attribute value for APP_AMOUNT using the alias name AppAmount.
     * @return the APP_AMOUNT
     */
    public BigDecimal getAppAmount() {
        return (BigDecimal)getAttributeInternal(APPAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_AMOUNT using the alias name AppAmount.
     * @param value value to set the APP_AMOUNT
     */
    public void setAppAmount(BigDecimal value) {
        setAttributeInternal(APPAMOUNT, value);
    }

    /**
     * Gets the attribute value for CERT_QUANTITY using the alias name CertQuantity.
     * @return the CERT_QUANTITY
     */
    public Number getCertQuantity() {
        return (Number)getAttributeInternal(CERTQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CERT_QUANTITY using the alias name CertQuantity.
     * @param value value to set the CERT_QUANTITY
     */
    public void setCertQuantity(Number value) {
        setAttributeInternal(CERTQUANTITY, value);
    }

    /**
     * Gets the attribute value for CERT_UNIT_PRICE using the alias name CertUnitPrice.
     * @return the CERT_UNIT_PRICE
     */
    public Number getCertUnitPrice() {
        return (Number)getAttributeInternal(CERTUNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for CERT_UNIT_PRICE using the alias name CertUnitPrice.
     * @param value value to set the CERT_UNIT_PRICE
     */
    public void setCertUnitPrice(Number value) {
        setAttributeInternal(CERTUNITPRICE, value);
    }

    /**
     * Gets the attribute value for CERT_AMOUNT using the alias name CertAmount.
     * @return the CERT_AMOUNT
     */
    public Number getCertAmount() {
        return (Number)getAttributeInternal(CERTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CERT_AMOUNT using the alias name CertAmount.
     * @param value value to set the CERT_AMOUNT
     */
    public void setCertAmount(Number value) {
        setAttributeInternal(CERTAMOUNT, value);
    }

    /**
     * Gets the attribute value for COMPLETION_DATE using the alias name CompletionDate.
     * @return the COMPLETION_DATE
     */
    public Date getCompletionDate() {
        return (Date)getAttributeInternal(COMPLETIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPLETION_DATE using the alias name CompletionDate.
     * @param value value to set the COMPLETION_DATE
     */
    public void setCompletionDate(Date value) {
        setAttributeInternal(COMPLETIONDATE, value);
    }

    /**
     * Gets the attribute value for PERCENT_COMPLETE using the alias name PercentComplete.
     * @return the PERCENT_COMPLETE
     */
    public Number getPercentComplete() {
        return (Number)getAttributeInternal(PERCENTCOMPLETE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERCENT_COMPLETE using the alias name PercentComplete.
     * @param value value to set the PERCENT_COMPLETE
     */
    public void setPercentComplete(Number value) {
        setAttributeInternal(PERCENTCOMPLETE, value);
    }

    /**
     * Gets the attribute value for FUNDED_AMOUNT using the alias name FundedAmount.
     * @return the FUNDED_AMOUNT
     */
    public Number getFundedAmount() {
        return (Number)getAttributeInternal(FUNDEDAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNDED_AMOUNT using the alias name FundedAmount.
     * @param value value to set the FUNDED_AMOUNT
     */
    public void setFundedAmount(Number value) {
        setAttributeInternal(FUNDEDAMOUNT, value);
    }

    /**
     * Gets the attribute value for INVOICED_AMOUNT using the alias name InvoicedAmount.
     * @return the INVOICED_AMOUNT
     */
    public Number getInvoicedAmount() {
        return (Number)getAttributeInternal(INVOICEDAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICED_AMOUNT using the alias name InvoicedAmount.
     * @param value value to set the INVOICED_AMOUNT
     */
    public void setInvoicedAmount(Number value) {
        setAttributeInternal(INVOICEDAMOUNT, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number)getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for BOQ_ITEM_DESC using the alias name BoqItemDesc.
     * @return the BOQ_ITEM_DESC
     */
    public String getBoqItemDesc() {
        return (String)getAttributeInternal(BOQITEMDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for BOQ_ITEM_DESC using the alias name BoqItemDesc.
     * @param value value to set the BOQ_ITEM_DESC
     */
    public void setBoqItemDesc(String value) {
        setAttributeInternal(BOQITEMDESC, value);
    }

    /**
     * Gets the attribute value for CATEGORY_ID using the alias name CategoryId.
     * @return the CATEGORY_ID
     */
    public BigDecimal getCategoryId() {
        return (BigDecimal)getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CATEGORY_ID using the alias name CategoryId.
     * @param value value to set the CATEGORY_ID
     */
    public void setCategoryId(BigDecimal value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for ITEM_SPEC using the alias name ItemSpec.
     * @return the ITEM_SPEC
     */
    public String getItemSpec() {
        return (String)getAttributeInternal(ITEMSPEC);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_SPEC using the alias name ItemSpec.
     * @param value value to set the ITEM_SPEC
     */
    public void setItemSpec(String value) {
        setAttributeInternal(ITEMSPEC, value);
    }

    /**
     * Gets the attribute value for CANCEL_REASON using the alias name CancelReason.
     * @return the CANCEL_REASON
     */
    public String getCancelReason() {
        return (String)getAttributeInternal(CANCELREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCEL_REASON using the alias name CancelReason.
     * @param value value to set the CANCEL_REASON
     */
    public void setCancelReason(String value) {
        setAttributeInternal(CANCELREASON, value);
    }

    /**
     * Gets the attribute value for CHANGE_REASON using the alias name ChangeReason.
     * @return the CHANGE_REASON
     */
    public String getChangeReason() {
        return (String)getAttributeInternal(CHANGEREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for CHANGE_REASON using the alias name ChangeReason.
     * @param value value to set the CHANGE_REASON
     */
    public void setChangeReason(String value) {
        setAttributeInternal(CHANGEREASON, value);
    }

    /**
     * Gets the attribute value for NOTE_TO_BUYER using the alias name NoteToBuyer.
     * @return the NOTE_TO_BUYER
     */
    public String getNoteToBuyer() {
        return (String)getAttributeInternal(NOTETOBUYER);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTE_TO_BUYER using the alias name NoteToBuyer.
     * @param value value to set the NOTE_TO_BUYER
     */
    public void setNoteToBuyer(String value) {
        setAttributeInternal(NOTETOBUYER, value);
    }

    /**
     * Gets the attribute value for NOTE_TO_SUPPLIER using the alias name NoteToSupplier.
     * @return the NOTE_TO_SUPPLIER
     */
    public String getNoteToSupplier() {
        return (String)getAttributeInternal(NOTETOSUPPLIER);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTE_TO_SUPPLIER using the alias name NoteToSupplier.
     * @param value value to set the NOTE_TO_SUPPLIER
     */
    public void setNoteToSupplier(String value) {
        setAttributeInternal(NOTETOSUPPLIER, value);
    }

    /**
     * Gets the attribute value for NEED_BY_DATE using the alias name NeedByDate.
     * @return the NEED_BY_DATE
     */
    public Date getNeedByDate() {
        return (Date)getAttributeInternal(NEEDBYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for NEED_BY_DATE using the alias name NeedByDate.
     * @param value value to set the NEED_BY_DATE
     */
    public void setNeedByDate(Date value) {
        setAttributeInternal(NEEDBYDATE, value);
    }

    /**
     * Gets the attribute value for PO_STATUS using the alias name PoStatus.
     * @return the PO_STATUS
     */
    public String getPoStatus() {
        return (String)getAttributeInternal(POSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_STATUS using the alias name PoStatus.
     * @param value value to set the PO_STATUS
     */
    public void setPoStatus(String value) {
        setAttributeInternal(POSTATUS, value);
    }

    /**
     * Gets the attribute value for CONT_LINE_NUMBER using the alias name ContLineNumber.
     * @return the CONT_LINE_NUMBER
     */
    public BigDecimal getContLineNumber() {
        return (BigDecimal)getAttributeInternal(CONTLINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_LINE_NUMBER using the alias name ContLineNumber.
     * @param value value to set the CONT_LINE_NUMBER
     */
    public void setContLineNumber(BigDecimal value) {
        setAttributeInternal(CONTLINENUMBER, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @return the TAX_AMOUNT
     */
    public Number getTaxAmount() {
        return (Number)getAttributeInternal(TAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @param value value to set the TAX_AMOUNT
     */
    public void setTaxAmount(Number value) {
        setAttributeInternal(TAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for TAX_CODE using the alias name TaxCode.
     * @return the TAX_CODE
     */
    public String getTaxCode() {
        return (String)getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_CODE using the alias name TaxCode.
     * @param value value to set the TAX_CODE
     */
    public void setTaxCode(String value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for TAX_RATE using the alias name TaxRate.
     * @return the TAX_RATE
     */
    public Number getTaxRate() {
        return (Number)getAttributeInternal(TAXRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE using the alias name TaxRate.
     * @param value value to set the TAX_RATE
     */
    public void setTaxRate(Number value) {
        setAttributeInternal(TAXRATE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_LINE_NUMBER using the alias name ContractLineNumber.
     * @return the CONTRACT_LINE_NUMBER
     */
    public String getContractLineNumber() {
        return (String)getAttributeInternal(CONTRACTLINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_LINE_NUMBER using the alias name ContractLineNumber.
     * @param value value to set the CONTRACT_LINE_NUMBER
     */
    public void setContractLineNumber(String value) {
        setAttributeInternal(CONTRACTLINENUMBER, value);
    }

    /**
     * Gets the attribute value for REL_LINE_NUMBER using the alias name RelLineNumber.
     * @return the REL_LINE_NUMBER
     */
    public String getRelLineNumber() {
        return (String)getAttributeInternal(RELLINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for REL_LINE_NUMBER using the alias name RelLineNumber.
     * @param value value to set the REL_LINE_NUMBER
     */
    public void setRelLineNumber(String value) {
        setAttributeInternal(RELLINENUMBER, value);
    }

    /**
     * Gets the attribute value for VARIATION using the alias name Variation.
     * @return the VARIATION
     */
    public String getVariation() {
        return (String)getAttributeInternal(VARIATION);
    }

    /**
     * Sets <code>value</code> as attribute value for VARIATION using the alias name Variation.
     * @param value value to set the VARIATION
     */
    public void setVariation(String value) {
        setAttributeInternal(VARIATION, value);
    }

    /**
     * Gets the attribute value for ECP_PERCENTAGE using the alias name EcpPercentage.
     * @return the ECP_PERCENTAGE
     */
    public Number getEcpPercentage() {
        return (Number)getAttributeInternal(ECPPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for ECP_PERCENTAGE using the alias name EcpPercentage.
     * @param value value to set the ECP_PERCENTAGE
     */
    public void setEcpPercentage(Number value) {
        setAttributeInternal(ECPPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for ECP_TOTAL_AMOUNT using the alias name EcpTotalAmount.
     * @return the ECP_TOTAL_AMOUNT
     */
    public Number getEcpTotalAmount() {
        return (Number)getAttributeInternal(ECPTOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for ECP_TOTAL_AMOUNT using the alias name EcpTotalAmount.
     * @param value value to set the ECP_TOTAL_AMOUNT
     */
    public void setEcpTotalAmount(Number value) {
        setAttributeInternal(ECPTOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for CONT_LINE_PAGE_NO using the alias name ContLinePageNo.
     * @return the CONT_LINE_PAGE_NO
     */
    public String getContLinePageNo() {
        return (String)getAttributeInternal(CONTLINEPAGENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_LINE_PAGE_NO using the alias name ContLinePageNo.
     * @param value value to set the CONT_LINE_PAGE_NO
     */
    public void setContLinePageNo(String value) {
        setAttributeInternal(CONTLINEPAGENO, value);
    }

    /**
     * Gets the attribute value for CONT_LINE_ITEM_NO using the alias name ContLineItemNo.
     * @return the CONT_LINE_ITEM_NO
     */
    public String getContLineItemNo() {
        return (String)getAttributeInternal(CONTLINEITEMNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_LINE_ITEM_NO using the alias name ContLineItemNo.
     * @param value value to set the CONT_LINE_ITEM_NO
     */
    public void setContLineItemNo(String value) {
        setAttributeInternal(CONTLINEITEMNO, value);
    }

    /**
     * Gets the attribute value for CONT_LINE_BILL_DTLS using the alias name ContLineBillDtls.
     * @return the CONT_LINE_BILL_DTLS
     */
    public String getContLineBillDtls() {
        return (String)getAttributeInternal(CONTLINEBILLDTLS);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_LINE_BILL_DTLS using the alias name ContLineBillDtls.
     * @param value value to set the CONT_LINE_BILL_DTLS
     */
    public void setContLineBillDtls(String value) {
        setAttributeInternal(CONTLINEBILLDTLS, value);
    }

    /**
     * Gets the attribute value for LINE_AMT_REMARK using the alias name LineAmtRemark.
     * @return the LINE_AMT_REMARK
     */
    public String getLineAmtRemark() {
        return (String)getAttributeInternal(LINEAMTREMARK);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_AMT_REMARK using the alias name LineAmtRemark.
     * @param value value to set the LINE_AMT_REMARK
     */
    public void setLineAmtRemark(String value) {
        setAttributeInternal(LINEAMTREMARK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryName_Tarns.
     * @return the CategoryName_Tarns
     */
    public String getCategoryName_Tarns() {
        return (String)getAttributeInternal(CATEGORYNAME_TARNS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryName_Tarns.
     * @param value value to set the  CategoryName_Tarns
     */
    public void setCategoryName_Tarns(String value) {
        setAttributeInternal(CATEGORYNAME_TARNS, value);
    }

    /**
     * Gets the attribute value for CONT_ADV using the alias name ContAdv.
     * @return the CONT_ADV
     */
    public Number getContAdv() {
        return (Number)getAttributeInternal(CONTADV);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_ADV using the alias name ContAdv.
     * @param value value to set the CONT_ADV
     */
    public void setContAdv(Number value) {
        setAttributeInternal(CONTADV, value);
    }

    /**
     * Gets the attribute value for CONT_ADV_AMT using the alias name ContAdvAmt.
     * @return the CONT_ADV_AMT
     */
    public Number getContAdvAmt() {
        return (Number)getAttributeInternal(CONTADVAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_ADV_AMT using the alias name ContAdvAmt.
     * @param value value to set the CONT_ADV_AMT
     */
    public void setContAdvAmt(Number value) {
        setAttributeInternal(CONTADVAMT, value);
    }

    /**
     * Gets the attribute value for CONT_ADV_REC using the alias name ContAdvRec.
     * @return the CONT_ADV_REC
     */
    public oracle.jbo.domain.Number getContAdvRec() {
        return (oracle.jbo.domain.Number)getAttributeInternal(CONTADVREC);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_ADV_REC using the alias name ContAdvRec.
     * @param value value to set the CONT_ADV_REC
     */
    public void setContAdvRec(oracle.jbo.domain.Number value) {
        setAttributeInternal(CONTADVREC, value);
    }

    /**
     * Gets the attribute value for CONT_ADV_REC_AMT using the alias name ContAdvRecAmt.
     * @return the CONT_ADV_REC_AMT
     */
    public Number getContAdvRecAmt() {
           oracle.jbo.domain.Number Amount =
           (this.getOrigAmount() == null ?
                                       new oracle.jbo.domain.Number(0) :
                                       this.getOrigAmount());
        oracle.jbo.domain.Number perc =
            (this.getContAdvRec() == null ?
                                       new oracle.jbo.domain.Number(0) :
                                       this.getContAdvRec());
        return (Amount.multiply(perc)).divide(100);

//        return (Number)getAttributeInternal(CONTADVRECAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_ADV_REC_AMT using the alias name ContAdvRecAmt.
     * @param value value to set the CONT_ADV_REC_AMT
     */
    public void setContAdvRecAmt(Number value) {
              setAttributeInternal(CONTADVRECAMT, value);
        }

    /**
     * Gets the attribute value for CONT_RET using the alias name ContRet.
     * @return the CONT_RET
     */
    public Number getContRet() {
        return (Number)getAttributeInternal(CONTRET);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_RET using the alias name ContRet.
     * @param value value to set the CONT_RET
     */
    public void setContRet(Number value) {
        setAttributeInternal(CONTRET, value);
    }

    /**
     * Gets the attribute value for CONT_RET_AMT using the alias name ContRetAmt.
     * @return the CONT_RET_AMT
     */
    public Number getContRetAmt() {
        return (Number)getAttributeInternal(CONTRETAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_RET_AMT using the alias name ContRetAmt.
     * @param value value to set the CONT_RET_AMT
     */
    public void setContRetAmt(Number value) {
        setAttributeInternal(CONTRETAMT, value);
    }

    /**
     * Gets the attribute value for CONT_RET_REC using the alias name ContRetRec.
     * @return the CONT_RET_REC
     */
    public Number getContRetRec() {
        return (Number)getAttributeInternal(CONTRETREC);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_RET_REC using the alias name ContRetRec.
     * @param value value to set the CONT_RET_REC
     */
    public void setContRetRec(Number value) {
        setAttributeInternal(CONTRETREC, value);
    }

    /**
     * Gets the attribute value for CONT_RET_REC_AMT using the alias name ContRetRecAmt.
     * @return the CONT_RET_REC_AMT
     */
    public oracle.jbo.domain.Number getContRetRecAmt() {
        oracle.jbo.domain.Number Amount =
          (this.getOrigAmount() == null ?
                                       new oracle.jbo.domain.Number(0) :
                                       this.getOrigAmount());
        oracle.jbo.domain.Number perc =
          (this.getContRetRec() == null ?
                                       new oracle.jbo.domain.Number(0) :
                                       this.getContRetRec());
        return (Amount.multiply(perc)).divide(100);
        //        return (Number)getAttributeInternal(CONTRETRECAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_RET_REC_AMT using the alias name ContRetRecAmt.
     * @param value value to set the CONT_RET_REC_AMT
     */
    public void setContRetRecAmt(oracle.jbo.domain.Number value) {
        setAttributeInternal(CONTRETRECAMT, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link XxscContractHeadersVO.
     */
    public Row getXxscContractHeadersVO() {
        return (Row)getAttributeInternal(XXSCCONTRACTHEADERSVO);
    }

    /**
     * Sets the master-detail link XxscContractHeadersVO between this object and <code>value</code>.
     */
    public void setXxscContractHeadersVO(Row value) {
        setAttributeInternal(XXSCCONTRACTHEADERSVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxscContractDelPlanVO.
     */
    public RowIterator getXxscContractDelPlanVO() {
        return (RowIterator)getAttributeInternal(XXSCCONTRACTDELPLANVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxscAttachmentVO.
     */
    public RowIterator getXxscAttachmentVO() {
        return (RowIterator)getAttributeInternal(XXSCATTACHMENTVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> prROVA.
     */
    public RowSet getprROVA() {
        return (RowSet)getAttributeInternal(PRROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> poROVA.
     */
    public RowSet getpoROVA() {
        return (RowSet)getAttributeInternal(POROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> projectTask_ROVA.
     */
    public RowSet getprojectTask_ROVA() {
        return (RowSet)getAttributeInternal(PROJECTTASK_ROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UOM_ROVA.
     */
    public RowSet getUOM_ROVA() {
        return (RowSet)getAttributeInternal(UOM_ROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> prLine_ROVA.
     */
    public RowSet getprLine_ROVA() {
        return (RowSet)getAttributeInternal(PRLINE_ROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> poLineROVA.
     */
    public RowSet getpoLineROVA() {
        return (RowSet)getAttributeInternal(POLINEROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UOM_ROVA_E.
     */
    public RowSet getUOM_ROVA_E() {
        return (RowSet)getAttributeInternal(UOM_ROVA_E);
    }

    /**
     * Gets the view accessor <code>RowSet</code> categoryROVA.
     */
    public RowSet getcategoryROVA() {
        return (RowSet)getAttributeInternal(CATEGORYROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> categoryROVA_E.
     */
    public RowSet getcategoryROVA_E() {
        return (RowSet)getAttributeInternal(CATEGORYROVA_E);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Variation_ROVO1.
     */
    public RowSet getVariation_ROVO1() {
        return (RowSet)getAttributeInternal(VARIATION_ROVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


}
