package view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 23 11:45:40 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxscContractLinesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxscContractLinesVOImpl() {
    }

    /**
     * Returns the variable value for BV_CONT_HID.
     * @return variable value for BV_CONT_HID
     */
    public String getBV_CONT_HID() {
        return (String)ensureVariableManager().getVariableValue("BV_CONT_HID");
    }

    /**
     * Sets <code>value</code> for variable BV_CONT_HID.
     * @param value value to bind as BV_CONT_HID
     */
    public void setBV_CONT_HID(String value) {
        ensureVariableManager().setVariableValue("BV_CONT_HID", value);
    }

    /**
     * Returns the variable value for BV_CONT_LID.
     * @return variable value for BV_CONT_LID
     */
    public String getBV_CONT_LID() {
        return (String)ensureVariableManager().getVariableValue("BV_CONT_LID");
    }

    /**
     * Sets <code>value</code> for variable BV_CONT_LID.
     * @param value value to bind as BV_CONT_LID
     */
    public void setBV_CONT_LID(String value) {
        ensureVariableManager().setVariableValue("BV_CONT_LID", value);
    }

    /**
     * Returns the variable value for BV_CONT_VER.
     * @return variable value for BV_CONT_VER
     */
    public String getBV_CONT_VER() {
        return (String)ensureVariableManager().getVariableValue("BV_CONT_VER");
    }

    /**
     * Sets <code>value</code> for variable BV_CONT_VER.
     * @param value value to bind as BV_CONT_VER
     */
    public void setBV_CONT_VER(String value) {
        ensureVariableManager().setVariableValue("BV_CONT_VER", value);
    }
}
